services:
  test-php:
    container_name: test-php
    build:
      context: ./
      dockerfile: Dockerfile
    user: ${UID:-1000}:${GID:-1000}
    volumes:
      - ./:/app
      - /app/vendor
    ports:
      - "8080:80"
    restart: unless-stopped
    stdin_open: true
    tty: true
