name: Continuous integration

on:
  workflow_dispatch: ~
  push:
    branches:
      - develop
      - main
      - feature/3.0
  pull_request:
    branches:
      - develop
      - main
      - feature/3.0

jobs:
  ci:
    name: Linting, tests and coverage
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        php:
          - "7.4"
          - "8.0"
          - "8.1"
          - "8.2"
          - "8.3"
          - "8.4"

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Setup PHP
        uses: shivammathur/setup-php@cf4cade2721270509d5b1c766ab3549210a39a2a # 2.33.0
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Ensure source code is linted
        run: composer exec phpcs -- src/

      - name: PHPUnit
        run: |
          case ${{ matrix.php }} in
            8.1|8.2|8.3|8.4 ) composer exec phpunit -- --configuration phpunit.ci.8.xml --coverage-xml ./.coverage;;
            *) composer exec phpunit -- --configuration phpunit.ci.xml --coverage-xml ./.coverage;;
          esac
        env:
          XDEBUG_MODE: coverage

      - name: PHPUnit threshold
        run: php ./phpunit-threshold.php
