name: PHP Lint and unit tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master, feat/v2-0-0]
  workflow_dispatch: ~

jobs:
  ci:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 5.6
          tools: composer:v1

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      # - name: Ensure source code is linted
      #   run: ./vendor/bin/phpcs src

      - name: Ensure unit test are green
        run: ./vendor/bin/phpunit -c phpunit.ci.xml
