name: PHPUnit Code Coverage Report

on:
  push:
    branches: [develop, master]
  pull_request:
    branches: [master, develop]
    paths:
      - '.github/reporting.yml'
      - '**.php'
  workflow_dispatch: ~

permissions:
  contents: write

jobs:
  ci:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 5.6
          tools: composer:v1

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: PHPUnit
        run: |
          ./vendor/bin/phpunit -c phpunit.ci.xml
        env:
          XDEBUG_MODE: coverage

      - name: Generate Coverage report
        run: |
          php CoverageGenerate.php >> Coverage.md
        env:
          XDEBUG_MODE: coverage

      - name: PHPStan Analysis
        run: |
          ./vendor/bin/phpstan analyse --configuration=phpstan.neon --memory-limit=1024M --error-format=md --no-progress >> 'Static Analysis.md'

      - name: Wiki checkout
        uses: actions/checkout@v4
        with:
          repository: ${{github.repository}}.wiki
          path: 'wiki'

      - name: Push
        run: |
          mv Coverage.md wiki
          mv 'Static Analysis.md' wiki
          cd wiki
          ls -la
          git config user.name actions-runner
          git config user.email actions-runner@github.com
          git add .
          git commit -m "Add Coverage and Analysis files" 
          git push
